[build]
target = ["x86_64-unknown-linux-musl"]
rustflags = ["-C", "target-feature=+crt-static"]

[profile.release]
strip = true
codegen-units = 1

[test]
target = ["x86_64-unknown-linux-musl"]
rustflags = ["-C", "target-feature=+crt-static"]
